version: '3.4'

services:
  klipper:
    build:
      dockerfile: ./klipper/Dockerfile
      context: .
    container_name: klipper
    ports:
      - 7125:7125
    restart: unless-stopped
    volumes:
      - gcode_files:/home/klippy/gcode_files
      - klipper_data:/home/klippy/.config
      - moonraker_data:/home/klippy/.moonraker
    devices:
      - /dev/serial/by-id/usb-1a86_USB_Serial-if00-port0:/dev/ttyUSB0 #根据实际情况更改

  fluidd:
    image: dimalo/fluidd
    restart: unless-stopped
    container_name: fluidd
    ports:
      - 8010:80
    depends_on: 
      - klipper
    links:
      - klipper:klipper

volumes: 
  gcode_files:
  moonraker_data:
  klipper_data:
 
